-- Minimal SILCE schema for cascade demo (Compra + Aposta + ApostaComprada + ReservaCotaBolao)

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SCHEMA LCE';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB002_APOSTADOR (
      NU_APOSTADOR BIGINT NOT NULL,
      NO_APOSTADOR VARCHAR(120),
      NU_CPF VARCHAR(20),
      CONSTRAINT PK_LCETB002 PRIMARY KEY (NU_APOSTADOR)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB012_SITUACAO_COMPRA (
      NU_SITUACAO_COMPRA BIGINT NOT NULL,
      DE_SITUACAO_COMPRA VARCHAR(120),
      CONSTRAINT PK_LCETB012 PRIMARY KEY (NU_SITUACAO_COMPRA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB008_SITUACAO_APOSTA (
      NU_SITUACAO_APOSTA BIGINT NOT NULL,
      DE_SITUACAO_APOSTA VARCHAR(120),
      CONSTRAINT PK_LCETB008 PRIMARY KEY (NU_SITUACAO_APOSTA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB060_STCO_RVRSA_COTA_BOLAO (
      NU_SITUACAO_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      NO_RESERVA_SITUACAO_COTA_BOLAO VARCHAR(120),
      DE_SITUACAO_RESERVA_COTA_BOLAO VARCHAR(120),
      CONSTRAINT PK_LCETB060 PRIMARY KEY (NU_SITUACAO_RESERVA_COTA_BOLAO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB013_COMPRA (
      NU_COMPRA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_SITUACAO_COMPRA BIGINT NOT NULL,
      NU_APOSTADOR BIGINT NOT NULL,
      NU_CD BIGINT,
      NU_TRANSACAO_DEBITO VARCHAR(64),
      NU_TRANSACAO_ESTORNO VARCHAR(64),
      NU_TRANSACAO BIGINT,
      DT_INICIO_COMPRA DATE,
      DT_EFETIVACAO_DEBITO DATE,
      HH_INICIO_COMPRA TIME,
      DT_FINALIZACAO_COMPRA DATE,
      HH_FINALIZACAO_COMPRA TIME,
      VR_TOTAL DECIMAL(15,2),
      VR_COMISSAO DECIMAL(15,2),
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      NU_PARTICAO BIGINT,
      NU_MES BIGINT,
      NU_MEIO_PAGAMENTO BIGINT,
      DE_ERRO_PAGAMENTO VARCHAR(255),
      IC_SUBCANAL_PAGAMENTO SMALLINT,
      DT_EXPIRACAO_PAGAMENTO DATE,
      HH_EXPIRACAO_PAGAMENTO TIME,
      IC_COMPRA_INTEGRADA CHAR(1),
      CONSTRAINT PK_LCETB013 PRIMARY KEY (NU_COMPRA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB059_RESERVA_COTA_BOLAO (
      NU_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      MM_RESERVA_COTA_BOLAO INTEGER NOT NULL,
      NU_PARTICAO INTEGER NOT NULL,
      CO_BOLAO_RESERVA_COTA VARCHAR(64),
      CO_COTA_BOLAO VARCHAR(64),
      NU_CANAL_DISTRIBUICAO BIGINT,
      AA_RESERVA_COTA_BOLAO INTEGER,
      TS_DATA_HORA_RESERVA_COTA TIMESTAMP,
      DT_EXPRO_RESERVA_COTA_BOLAO DATE,
      HH_EXPRO_RESERVA_COTA_BOLAO TIME,
      NU_COTA_RESERVADA INTEGER,
      QT_COTA_TOTAL_BOLAO INTEGER,
      VR_COTA_RESERVADA DECIMAL(15,2),
      VR_TARIFA_SERVICO DECIMAL(15,2),
      DT_REGISTRO_BOLAO DATE,
      HH_REGISTRO_BOLAO TIME,
      NU_TERMINAL_LOTERICO INTEGER,
      DE_COTA_BOLAO VARCHAR(500),
      NU_SITUACAO_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      VR_CUSTEIO_COTA DECIMAL(15,2),
      VR_TARIFA_CUSTEIO_COTA DECIMAL(15,2),
      NU_TRANSACAO_RESERVA_COTA BIGINT,
      CONSTRAINT PK_LCETB059 PRIMARY KEY (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB011_APOSTA (
      NU_APOSTA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_COMPRA BIGINT NOT NULL,
      NU_MODALIDADE_JOGO SMALLINT,
      IC_TIPO_CONCURSO SMALLINT,
      IC_SURPRESINHA SMALLINT,
      VR_APOSTA DECIMAL(15,2),
      NU_PARTICAO BIGINT,
      NU_CONCURSO_ALVO INTEGER,
      NU_MES BIGINT,
      TS_INCLUSAO_APOSTA_CARRINHO TIMESTAMP,
      IC_SUBCANAL_APOSTA SMALLINT,
      NU_VINCULO_APOSTA_ESPELHO BIGINT,
      NU_COMBO_APOSTA BIGINT,
      IC_COTA_BOLAO CHAR(1),
      NU_RESERVA_COTA_BOLAO BIGINT,
      MM_RESERVA_COTA_BOLAO INTEGER,
      NU_PARTICAO_COTA_BOLAO INTEGER,
      DE_PROGNOSTICO VARCHAR(512),
      QT_TEIMOSINHA INTEGER,
      QT_APOSTA INTEGER,
      MM_SORTE INTEGER,
      IC_ESPELHO CHAR(1),
      DE_PROGNOSTICO_TREVO VARCHAR(512),
      NU_EQUIPE_ESPORTIVA INTEGER,
      CONSTRAINT PK_LCETB011 PRIMARY KEY (NU_APOSTA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB009_APOSTA_COMPRADA (
      NU_APOSTA_COMPRADA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_PREMIO BIGINT,
      NU_APOSTA_ORIGEM BIGINT,
      NU_TRANSACAO_APOSTA BIGINT,
      NU_TRANSACAO_DEVOLUCAO VARCHAR(64),
      NU_CONCURSO_INICIAL INTEGER,
      NU_SERIE_BILHETE VARCHAR(64),
      IC_BILHETE_TROCA CHAR(1),
      DT_INICIO_APOSTA_COMPRADA DATE,
      HH_INICIO_APOSTA_COMPRADA TIME,
      DT_ENVIO_APOSTA_SISPL DATE,
      HH_ENVIO_APOSTA_SISPL TIME,
      DT_EFTCO_APOSTA_SISPL DATE,
      HH_EFTCO_APOSTA_SISPL TIME,
      DT_FINALIZACAO_PROCESSAMENTO DATE,
      HH_FINALIZACAO_PROCESSAMENTO TIME,
      NU_SITUACAO_APOSTA BIGINT NOT NULL,
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      DE_ERRO_RESGATE VARCHAR(255),
      VR_COMISSAO DECIMAL(15,2),
      NU_APOSTA BIGINT NOT NULL,
      IC_SUBCANAL_PAGAMENTO SMALLINT,
      IC_BLOQUEIO_DEVOLUCAO CHAR(1),
      DE_MENSAGEM_ERRO_APOSTA VARCHAR(255),
      NU_PARTICAO BIGINT,
      NU_MES BIGINT,
      CONSTRAINT PK_LCETB009 PRIMARY KEY (NU_APOSTA_COMPRADA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCETB011_APOSTA
    ADD CONSTRAINT FK_LCETB011_LCETB059
    FOREIGN KEY (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO_COTA_BOLAO)
    REFERENCES LCE.LCETB059_RESERVA_COTA_BOLAO
      (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO)';
END@

-- Seed minimum lookup/reference data used by ApostaCascadeDemoBean
MERGE INTO LCE.LCETB002_APOSTADOR AS T
USING (VALUES (1, 'Apostador Demo', '12345678901')) AS S(NU_APOSTADOR, NO_APOSTADOR, NU_CPF)
ON T.NU_APOSTADOR = S.NU_APOSTADOR
WHEN NOT MATCHED THEN
  INSERT (NU_APOSTADOR, NO_APOSTADOR, NU_CPF)
  VALUES (S.NU_APOSTADOR, S.NO_APOSTADOR, S.NU_CPF)@

MERGE INTO LCE.LCETB012_SITUACAO_COMPRA AS T
USING (VALUES (1, 'CARRINHO')) AS S(NU_SITUACAO_COMPRA, DE_SITUACAO_COMPRA)
ON T.NU_SITUACAO_COMPRA = S.NU_SITUACAO_COMPRA
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_COMPRA, DE_SITUACAO_COMPRA)
  VALUES (S.NU_SITUACAO_COMPRA, S.DE_SITUACAO_COMPRA)@

MERGE INTO LCE.LCETB008_SITUACAO_APOSTA AS T
USING (VALUES (1, 'NAO_REGISTRADA')) AS S(NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
ON T.NU_SITUACAO_APOSTA = S.NU_SITUACAO_APOSTA
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
  VALUES (S.NU_SITUACAO_APOSTA, S.DE_SITUACAO_APOSTA)@

MERGE INTO LCE.LCETB060_STCO_RVRSA_COTA_BOLAO AS T
USING (VALUES (2, 'RESERVADA', 'RESERVADA')) AS S(NU_SITUACAO_RESERVA_COTA_BOLAO, NO_RESERVA_SITUACAO_COTA_BOLAO, DE_SITUACAO_RESERVA_COTA_BOLAO)
ON T.NU_SITUACAO_RESERVA_COTA_BOLAO = S.NU_SITUACAO_RESERVA_COTA_BOLAO
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_RESERVA_COTA_BOLAO, NO_RESERVA_SITUACAO_COTA_BOLAO, DE_SITUACAO_RESERVA_COTA_BOLAO)
  VALUES (S.NU_SITUACAO_RESERVA_COTA_BOLAO, S.NO_RESERVA_SITUACAO_COTA_BOLAO, S.DE_SITUACAO_RESERVA_COTA_BOLAO)@
