-- Minimal SILCE schema for cascade demo (Compra + Aposta + ApostaComprada + ReservaCotaBolao)

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE 'CREATE SCHEMA LCE';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE SEQUENCE LCE.LCESQ059_NU_RESERVA_COTA_BOLAO
      AS BIGINT
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      NO CYCLE
      CACHE 20';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCEVW001_UF (
      NU_UF_IBGE BIGINT NOT NULL,
      SG_UF VARCHAR(2),
      NO_UF VARCHAR(60),
      CONSTRAINT PK_LCEVW001 PRIMARY KEY (NU_UF_IBGE)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCEVW002_MUNICIPIO (
      NU_DV_IBGE BIGINT NOT NULL,
      NU_MUNICIPIO_IBGE BIGINT NOT NULL,
      NU_UF_IBGE_L99 BIGINT NOT NULL,
      NO_MUNICIPIO VARCHAR(120),
      CONSTRAINT PK_LCEVW002 PRIMARY KEY (NU_DV_IBGE, NU_MUNICIPIO_IBGE, NU_UF_IBGE_L99)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB001_SITUACAO_APOSTADOR (
      NU_SITUACAO_APOSTADOR BIGINT NOT NULL,
      DE_SITUACAO_APOSTADOR VARCHAR(120),
      CONSTRAINT PK_LCETB001 PRIMARY KEY (NU_SITUACAO_APOSTADOR)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB003_TERMO_ADESAO (
      NU_VERSAO_TERMO_ADESAO BIGINT NOT NULL,
      DE_CONTEUDO_TERMO_ADESAO CLOB(64K),
      TS_INICIO_VIGENCIA_TERMO TIMESTAMP,
      TS_CRIACAO_TERMO_ADESAO TIMESTAMP,
      TS_ALTERACAO_TERMO_ADESAO TIMESTAMP,
      CONSTRAINT PK_LCETB003 PRIMARY KEY (NU_VERSAO_TERMO_ADESAO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCEVW007_CATEGORIA_LOTERICA (
      NU_CATEGORIA_005 BIGINT NOT NULL,
      NO_CATEGORIA_005 VARCHAR(120),
      CONSTRAINT PK_LCEVW007 PRIMARY KEY (NU_CATEGORIA_005)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCEVW008_TIPO_SITUACAO (
      NU_SITUACAO_007 BIGINT NOT NULL,
      NO_SITUACAO_007 VARCHAR(120),
      CONSTRAINT PK_LCEVW008 PRIMARY KEY (NU_SITUACAO_007)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCEVW004_LOTERICA (
      NU_CD BIGINT NOT NULL,
      NO_FANTASIA VARCHAR(120),
      NO_RAZAO_SOCIAL VARCHAR(120),
      NO_LOGRADOURO VARCHAR(120),
      NU_UF_IBGE_L98 BIGINT,
      NU_MNCPO_IBGE_L98 BIGINT,
      NU_DV_IBGE_L98 BIGINT,
      NO_BAIRRO VARCHAR(120),
      NO_MUNICIPIO VARCHAR(120),
      NO_UF VARCHAR(60),
      NU_POLO_CD BIGINT,
      NU_DV_CD BIGINT,
      NU_CEP VARCHAR(16),
      NU_CATEGORIA_005 BIGINT,
      NU_SITUACAO_C04 BIGINT,
      CONSTRAINT PK_LCEVW004 PRIMARY KEY (NU_CD)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42711' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCEVW004_LOTERICA
    ADD COLUMN NU_CATEGORIA_005 BIGINT';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42711' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCEVW004_LOTERICA
    ADD COLUMN NU_SITUACAO_C04 BIGINT';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB002_APOSTADOR (
      NU_APOSTADOR BIGINT NOT NULL,
      NU_CPF VARCHAR(20),
      DE_EMAIL VARCHAR(255),
      NO_APOSTADOR VARCHAR(120),
      DT_NASCIMENTO DATE,
      DT_ULTIMO_ACESSO DATE,
      TS_ULTIMO_ERRO_LOGIN TIMESTAMP,
      TS_BLOQUEIO_APOSTADOR TIMESTAMP,
      QT_ERRO_LOGIN INTEGER,
      CO_DDD VARCHAR(4),
      NU_CELULAR VARCHAR(20),
      NU_CEP VARCHAR(16),
      IC_NOTICIA CHAR(1),
      NU_DV_IBGE BIGINT,
      NU_MUNICIPIO_IBGE BIGINT,
      NU_UF_IBGE_L99 BIGINT,
      NU_SITUACAO_APOSTADOR BIGINT,
      TS_CADASTRO TIMESTAMP,
      NU_CD BIGINT,
      NU_CONFIGURACAO_RAPIDAO BIGINT,
      IC_SEXO CHAR(1),
      NU_VERSAO_TERMO_ADESAO BIGINT,
      TS_ACEITE_TERMO_ADESAO TIMESTAMP,
      DE_CUSTOMER_MERCADO_PAGO VARCHAR(255),
      TS_SELECAO_LOTERICA TIMESTAMP,
      VR_MXMO_SLNDO_APSTA_DIA DECIMAL(15,2),
      VR_MXMO_APROVADO_APSTA_DIA DECIMAL(15,2),
      DT_ALT_VR_MXMO_SELECIONADO DATE,
      IC_SUBCANAL_CADASTRO SMALLINT,
      IC_RESPOSTA CHAR(1),
      TS_AVALIACAO_RESPOSTA TIMESTAMP,
      TS_AVALIACAO_PROXIMA_RESPOSTA TIMESTAMP,
      TS_ULTIMA_CONSULTA_BLOQUEIO TIMESTAMP,
      CONSTRAINT PK_LCETB002 PRIMARY KEY (NU_APOSTADOR)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB012_SITUACAO_COMPRA (
      NU_SITUACAO_COMPRA BIGINT NOT NULL,
      DE_SITUACAO_COMPRA VARCHAR(120),
      CONSTRAINT PK_LCETB012 PRIMARY KEY (NU_SITUACAO_COMPRA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB008_SITUACAO_APOSTA (
      NU_SITUACAO_APOSTA BIGINT NOT NULL,
      DE_SITUACAO_APOSTA VARCHAR(120),
      CONSTRAINT PK_LCETB008 PRIMARY KEY (NU_SITUACAO_APOSTA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB052_TIPO_COMBO (
      NU_TIPO_COMBO BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      NO_TIPO_COMBO VARCHAR(120),
      DE_TIPO_COMBO VARCHAR(255),
      NU_ORDEM_TIPO_COMBO INTEGER,
      DT_CRIACAO_TIPO_COMBO DATE,
      IC_TIPO_COMBO_DISPONIVEL CHAR(1),
      CONSTRAINT PK_LCETB052 PRIMARY KEY (NU_TIPO_COMBO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB046_COMBO_APOSTA (
      NU_COMBO_APOSTA BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      NU_TIPO_COMBO BIGINT NOT NULL,
      NU_MES BIGINT,
      NU_PARTICAO BIGINT,
      CONSTRAINT PK_LCETB046 PRIMARY KEY (NU_COMBO_APOSTA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCETB046_COMBO_APOSTA
    ADD CONSTRAINT FK_LCETB046_LCETB052
    FOREIGN KEY (NU_TIPO_COMBO)
    REFERENCES LCE.LCETB052_TIPO_COMBO (NU_TIPO_COMBO)';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB060_STCO_RVRSA_COTA_BOLAO (
      NU_SITUACAO_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      NO_RESERVA_SITUACAO_COTA_BOLAO VARCHAR(120),
      DE_SITUACAO_RESERVA_COTA_BOLAO VARCHAR(120),
      CONSTRAINT PK_LCETB060 PRIMARY KEY (NU_SITUACAO_RESERVA_COTA_BOLAO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB013_COMPRA (
      NU_COMPRA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_SITUACAO_COMPRA BIGINT NOT NULL,
      NU_APOSTADOR BIGINT NOT NULL,
      NU_CD BIGINT,
      NU_TRANSACAO_DEBITO VARCHAR(64),
      NU_TRANSACAO_ESTORNO VARCHAR(64),
      NU_TRANSACAO BIGINT,
      DT_INICIO_COMPRA DATE,
      DT_EFETIVACAO_DEBITO DATE,
      HH_INICIO_COMPRA TIME,
      DT_FINALIZACAO_COMPRA DATE,
      HH_FINALIZACAO_COMPRA TIME,
      VR_TOTAL DECIMAL(15,2),
      VR_COMISSAO DECIMAL(15,2),
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      NU_PARTICAO BIGINT,
      NU_MES BIGINT,
      NU_MEIO_PAGAMENTO BIGINT,
      DE_ERRO_PAGAMENTO VARCHAR(255),
      IC_SUBCANAL_PAGAMENTO SMALLINT,
      DT_EXPIRACAO_PAGAMENTO DATE,
      HH_EXPIRACAO_PAGAMENTO TIME,
      IC_COMPRA_INTEGRADA CHAR(1),
      CONSTRAINT PK_LCETB013 PRIMARY KEY (NU_COMPRA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB059_RESERVA_COTA_BOLAO (
      NU_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      MM_RESERVA_COTA_BOLAO INTEGER NOT NULL,
      NU_PARTICAO INTEGER NOT NULL,
      CO_BOLAO_RESERVA_COTA VARCHAR(64),
      CO_COTA_BOLAO VARCHAR(64),
      NU_CANAL_DISTRIBUICAO BIGINT,
      AA_RESERVA_COTA_BOLAO INTEGER,
      TS_DATA_HORA_RESERVA_COTA TIMESTAMP,
      DT_EXPRO_RESERVA_COTA_BOLAO DATE,
      HH_EXPRO_RESERVA_COTA_BOLAO TIME,
      NU_COTA_RESERVADA INTEGER,
      QT_COTA_TOTAL_BOLAO INTEGER,
      VR_COTA_RESERVADA DECIMAL(15,2),
      VR_TARIFA_SERVICO DECIMAL(15,2),
      DT_REGISTRO_BOLAO DATE,
      HH_REGISTRO_BOLAO TIME,
      NU_TERMINAL_LOTERICO INTEGER,
      DE_COTA_BOLAO VARCHAR(500),
      NU_SITUACAO_RESERVA_COTA_BOLAO BIGINT NOT NULL,
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      VR_CUSTEIO_COTA DECIMAL(15,2),
      VR_TARIFA_CUSTEIO_COTA DECIMAL(15,2),
      NU_TRANSACAO_RESERVA_COTA BIGINT,
      CONSTRAINT PK_LCETB059 PRIMARY KEY (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB011_APOSTA (
      NU_APOSTA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_COMPRA BIGINT NOT NULL,
      NU_MODALIDADE_JOGO SMALLINT,
      IC_TIPO_CONCURSO SMALLINT,
      IC_SURPRESINHA SMALLINT,
      VR_APOSTA DECIMAL(15,2),
      NU_PARTICAO BIGINT,
      NU_CONCURSO_ALVO INTEGER,
      NU_MES BIGINT,
      TS_INCLUSAO_APOSTA_CARRINHO TIMESTAMP,
      IC_SUBCANAL_APOSTA SMALLINT,
      NU_VINCULO_APOSTA_ESPELHO BIGINT,
      NU_COMBO_APOSTA BIGINT,
      IC_COTA_BOLAO CHAR(1),
      NU_RESERVA_COTA_BOLAO BIGINT,
      MM_RESERVA_COTA_BOLAO INTEGER,
      NU_PARTICAO_COTA_BOLAO INTEGER,
      DE_PROGNOSTICO VARCHAR(512),
      QT_TEIMOSINHA INTEGER,
      QT_APOSTA INTEGER,
      MM_SORTE INTEGER,
      IC_ESPELHO CHAR(1),
      DE_PROGNOSTICO_TREVO VARCHAR(512),
      NU_EQUIPE_ESPORTIVA INTEGER,
      CONSTRAINT PK_LCETB011 PRIMARY KEY (NU_APOSTA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    CREATE TABLE LCE.LCETB009_APOSTA_COMPRADA (
      NU_APOSTA_COMPRADA BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      NU_PREMIO BIGINT,
      NU_APOSTA_ORIGEM BIGINT,
      NU_TRANSACAO_APOSTA BIGINT,
      NU_TRANSACAO_DEVOLUCAO VARCHAR(64),
      NU_CONCURSO_INICIAL INTEGER,
      NU_SERIE_BILHETE VARCHAR(64),
      IC_BILHETE_TROCA CHAR(1),
      DT_INICIO_APOSTA_COMPRADA DATE,
      HH_INICIO_APOSTA_COMPRADA TIME,
      DT_ENVIO_APOSTA_SISPL DATE,
      HH_ENVIO_APOSTA_SISPL TIME,
      DT_EFTCO_APOSTA_SISPL DATE,
      HH_EFTCO_APOSTA_SISPL TIME,
      DT_FINALIZACAO_PROCESSAMENTO DATE,
      HH_FINALIZACAO_PROCESSAMENTO TIME,
      NU_SITUACAO_APOSTA BIGINT NOT NULL,
      TS_ALTERACAO_SITUACAO TIMESTAMP,
      DE_ERRO_RESGATE VARCHAR(255),
      VR_COMISSAO DECIMAL(15,2),
      NU_APOSTA BIGINT NOT NULL,
      IC_SUBCANAL_PAGAMENTO SMALLINT,
      IC_BLOQUEIO_DEVOLUCAO CHAR(1),
      DE_MENSAGEM_ERRO_APOSTA VARCHAR(255),
      NU_PARTICAO BIGINT,
      NU_MES BIGINT,
      CONSTRAINT PK_LCETB009 PRIMARY KEY (NU_APOSTA_COMPRADA)
    )';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCETB011_APOSTA
    ADD CONSTRAINT FK_LCETB011_LCETB046
    FOREIGN KEY (NU_COMBO_APOSTA)
    REFERENCES LCE.LCETB046_COMBO_APOSTA (NU_COMBO_APOSTA)';
END@

BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' BEGIN END;
  EXECUTE IMMEDIATE '
    ALTER TABLE LCE.LCETB011_APOSTA
    ADD CONSTRAINT FK_LCETB011_LCETB059
    FOREIGN KEY (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO_COTA_BOLAO)
    REFERENCES LCE.LCETB059_RESERVA_COTA_BOLAO
      (NU_RESERVA_COTA_BOLAO, MM_RESERVA_COTA_BOLAO, NU_PARTICAO)';
END@

-- Seed minimum lookup/reference data used by ApostaCascadeDemoBean
MERGE INTO LCE.LCEVW001_UF AS T
USING (VALUES (0, 'NA', 'NAO INFORMADO')) AS S(NU_UF_IBGE, SG_UF, NO_UF)
ON T.NU_UF_IBGE = S.NU_UF_IBGE
WHEN NOT MATCHED THEN
  INSERT (NU_UF_IBGE, SG_UF, NO_UF)
  VALUES (S.NU_UF_IBGE, S.SG_UF, S.NO_UF)@

MERGE INTO LCE.LCEVW002_MUNICIPIO AS T
USING (VALUES (0, 0, 0, 'NAO INFORMADO')) AS S(NU_DV_IBGE, NU_MUNICIPIO_IBGE, NU_UF_IBGE_L99, NO_MUNICIPIO)
ON T.NU_DV_IBGE = S.NU_DV_IBGE AND T.NU_MUNICIPIO_IBGE = S.NU_MUNICIPIO_IBGE AND T.NU_UF_IBGE_L99 = S.NU_UF_IBGE_L99
WHEN NOT MATCHED THEN
  INSERT (NU_DV_IBGE, NU_MUNICIPIO_IBGE, NU_UF_IBGE_L99, NO_MUNICIPIO)
  VALUES (S.NU_DV_IBGE, S.NU_MUNICIPIO_IBGE, S.NU_UF_IBGE_L99, S.NO_MUNICIPIO)@

MERGE INTO LCE.LCETB001_SITUACAO_APOSTADOR AS T
USING (VALUES (1, 'ATIVO')) AS S(NU_SITUACAO_APOSTADOR, DE_SITUACAO_APOSTADOR)
ON T.NU_SITUACAO_APOSTADOR = S.NU_SITUACAO_APOSTADOR
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_APOSTADOR, DE_SITUACAO_APOSTADOR)
  VALUES (S.NU_SITUACAO_APOSTADOR, S.DE_SITUACAO_APOSTADOR)@

MERGE INTO LCE.LCETB003_TERMO_ADESAO AS T
USING (
  VALUES (1, 'TERMO DEMO', CURRENT TIMESTAMP, CURRENT TIMESTAMP, CURRENT TIMESTAMP)
) AS S(NU_VERSAO_TERMO_ADESAO, DE_CONTEUDO_TERMO_ADESAO, TS_INICIO_VIGENCIA_TERMO, TS_CRIACAO_TERMO_ADESAO, TS_ALTERACAO_TERMO_ADESAO)
ON T.NU_VERSAO_TERMO_ADESAO = S.NU_VERSAO_TERMO_ADESAO
WHEN NOT MATCHED THEN
  INSERT (NU_VERSAO_TERMO_ADESAO, DE_CONTEUDO_TERMO_ADESAO, TS_INICIO_VIGENCIA_TERMO, TS_CRIACAO_TERMO_ADESAO, TS_ALTERACAO_TERMO_ADESAO)
  VALUES (S.NU_VERSAO_TERMO_ADESAO, S.DE_CONTEUDO_TERMO_ADESAO, S.TS_INICIO_VIGENCIA_TERMO, S.TS_CRIACAO_TERMO_ADESAO, S.TS_ALTERACAO_TERMO_ADESAO)@

MERGE INTO LCE.LCEVW007_CATEGORIA_LOTERICA AS T
USING (VALUES (1, 'DEMO')) AS S(NU_CATEGORIA_005, NO_CATEGORIA_005)
ON T.NU_CATEGORIA_005 = S.NU_CATEGORIA_005
WHEN NOT MATCHED THEN
  INSERT (NU_CATEGORIA_005, NO_CATEGORIA_005)
  VALUES (S.NU_CATEGORIA_005, S.NO_CATEGORIA_005)@

MERGE INTO LCE.LCEVW008_TIPO_SITUACAO AS T
USING (VALUES (1, 'ATIVA')) AS S(NU_SITUACAO_007, NO_SITUACAO_007)
ON T.NU_SITUACAO_007 = S.NU_SITUACAO_007
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_007, NO_SITUACAO_007)
  VALUES (S.NU_SITUACAO_007, S.NO_SITUACAO_007)@

MERGE INTO LCE.LCEVW004_LOTERICA AS T
USING (VALUES (1, 'LOTERICA DEMO', 'LOTERICA DEMO', NULL, 0, 0, 0, NULL, 'NAO INFORMADO', 'NA', 0, 0, NULL, 1, 1))
  AS S(NU_CD, NO_FANTASIA, NO_RAZAO_SOCIAL, NO_LOGRADOURO, NU_UF_IBGE_L98, NU_MNCPO_IBGE_L98, NU_DV_IBGE_L98, NO_BAIRRO, NO_MUNICIPIO, NO_UF, NU_POLO_CD, NU_DV_CD, NU_CEP, NU_CATEGORIA_005, NU_SITUACAO_C04)
ON T.NU_CD = S.NU_CD
WHEN NOT MATCHED THEN
  INSERT (NU_CD, NO_FANTASIA, NO_RAZAO_SOCIAL, NO_LOGRADOURO, NU_UF_IBGE_L98, NU_MNCPO_IBGE_L98, NU_DV_IBGE_L98, NO_BAIRRO, NO_MUNICIPIO, NO_UF, NU_POLO_CD, NU_DV_CD, NU_CEP, NU_CATEGORIA_005, NU_SITUACAO_C04)
  VALUES (S.NU_CD, S.NO_FANTASIA, S.NO_RAZAO_SOCIAL, S.NO_LOGRADOURO, S.NU_UF_IBGE_L98, S.NU_MNCPO_IBGE_L98, S.NU_DV_IBGE_L98, S.NO_BAIRRO, S.NO_MUNICIPIO, S.NO_UF, S.NU_POLO_CD, S.NU_DV_CD, S.NU_CEP, S.NU_CATEGORIA_005, S.NU_SITUACAO_C04)@

UPDATE LCE.LCEVW004_LOTERICA
SET
  NU_CATEGORIA_005 = COALESCE(NU_CATEGORIA_005, 1),
  NU_SITUACAO_C04 = COALESCE(NU_SITUACAO_C04, 1),
  NU_POLO_CD = COALESCE(NU_POLO_CD, 0),
  NU_DV_CD = COALESCE(NU_DV_CD, 0)
WHERE NU_CD = 1@

MERGE INTO LCE.LCETB002_APOSTADOR AS T
USING (
  VALUES (
    108,
    '64888861068',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0,
    0,
    0,
    1,
    NULL,
    1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  )
) AS S(
  NU_APOSTADOR,
  NU_CPF,
  DE_EMAIL,
  NO_APOSTADOR,
  DT_NASCIMENTO,
  DT_ULTIMO_ACESSO,
  TS_ULTIMO_ERRO_LOGIN,
  TS_BLOQUEIO_APOSTADOR,
  QT_ERRO_LOGIN,
  CO_DDD,
  NU_CELULAR,
  NU_CEP,
  NU_DV_IBGE,
  NU_MUNICIPIO_IBGE,
  NU_UF_IBGE_L99,
  NU_SITUACAO_APOSTADOR,
  TS_CADASTRO,
  NU_CD,
  NU_CONFIGURACAO_RAPIDAO,
  IC_SEXO,
  NU_VERSAO_TERMO_ADESAO,
  TS_ACEITE_TERMO_ADESAO,
  DE_CUSTOMER_MERCADO_PAGO,
  TS_SELECAO_LOTERICA,
  VR_MXMO_SLNDO_APSTA_DIA,
  VR_MXMO_APROVADO_APSTA_DIA,
  DT_ALT_VR_MXMO_SELECIONADO,
  IC_SUBCANAL_CADASTRO,
  IC_RESPOSTA,
  TS_ULTIMA_CONSULTA_BLOQUEIO
)
ON T.NU_APOSTADOR = S.NU_APOSTADOR
WHEN NOT MATCHED THEN
  INSERT (
    NU_APOSTADOR,
    NU_CPF,
    DE_EMAIL,
    NO_APOSTADOR,
    DT_NASCIMENTO,
    DT_ULTIMO_ACESSO,
    TS_ULTIMO_ERRO_LOGIN,
    TS_BLOQUEIO_APOSTADOR,
    QT_ERRO_LOGIN,
    CO_DDD,
    NU_CELULAR,
    NU_CEP,
    NU_DV_IBGE,
    NU_MUNICIPIO_IBGE,
    NU_UF_IBGE_L99,
    NU_SITUACAO_APOSTADOR,
    TS_CADASTRO,
    NU_CD,
    NU_CONFIGURACAO_RAPIDAO,
    IC_SEXO,
    NU_VERSAO_TERMO_ADESAO,
    TS_ACEITE_TERMO_ADESAO,
    DE_CUSTOMER_MERCADO_PAGO,
    TS_SELECAO_LOTERICA,
    VR_MXMO_SLNDO_APSTA_DIA,
    VR_MXMO_APROVADO_APSTA_DIA,
    DT_ALT_VR_MXMO_SELECIONADO,
    IC_SUBCANAL_CADASTRO,
    IC_RESPOSTA,
    TS_ULTIMA_CONSULTA_BLOQUEIO
  )
  VALUES (
    S.NU_APOSTADOR,
    S.NU_CPF,
    S.DE_EMAIL,
    S.NO_APOSTADOR,
    S.DT_NASCIMENTO,
    S.DT_ULTIMO_ACESSO,
    S.TS_ULTIMO_ERRO_LOGIN,
    S.TS_BLOQUEIO_APOSTADOR,
    S.QT_ERRO_LOGIN,
    S.CO_DDD,
    S.NU_CELULAR,
    S.NU_CEP,
    S.NU_DV_IBGE,
    S.NU_MUNICIPIO_IBGE,
    S.NU_UF_IBGE_L99,
    S.NU_SITUACAO_APOSTADOR,
    S.TS_CADASTRO,
    S.NU_CD,
    S.NU_CONFIGURACAO_RAPIDAO,
    S.IC_SEXO,
    S.NU_VERSAO_TERMO_ADESAO,
    S.TS_ACEITE_TERMO_ADESAO,
    S.DE_CUSTOMER_MERCADO_PAGO,
    S.TS_SELECAO_LOTERICA,
    S.VR_MXMO_SLNDO_APSTA_DIA,
    S.VR_MXMO_APROVADO_APSTA_DIA,
    S.DT_ALT_VR_MXMO_SELECIONADO,
    S.IC_SUBCANAL_CADASTRO,
    S.IC_RESPOSTA,
    S.TS_ULTIMA_CONSULTA_BLOQUEIO
  )@

MERGE INTO LCE.LCETB012_SITUACAO_COMPRA AS T
USING (
  VALUES
    (1, 'CARRINHO'),
    (2, 'DEBITO_INICIADO'),
    (3, 'DEBITO_NAO_AUTORIZADO'),
    (4, 'ESTORNADA'),
    (5, 'CANCELADA'),
    (6, 'DEBITO_REALIZADO'),
    (7, 'EM_PROCESSAMENTO'),
    (8, 'FINALIZADA'),
    (9, 'EM_PROCESSAMENTO_REPRESADA'),
    (10, 'AGUARDANDO_PAGAMENTO_PIX'),
    (11, 'AGUARDANDO_DEVOLUCAO_PIX'),
    (12, 'CANCELADA_PAGAMENTO_NAO_IDENTIFICADO_TEMPO_LIMITE'),
    (13, 'FINALIZADA_TODAS_APOSTAS_EFETIVADAS'),
    (14, 'FINALIZADA_CONTEM_APOSTAS_NAO_EFETIVADAS')
) AS S(NU_SITUACAO_COMPRA, DE_SITUACAO_COMPRA)
ON T.NU_SITUACAO_COMPRA = S.NU_SITUACAO_COMPRA
WHEN MATCHED THEN
  UPDATE SET DE_SITUACAO_COMPRA = S.DE_SITUACAO_COMPRA
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_COMPRA, DE_SITUACAO_COMPRA)
  VALUES (S.NU_SITUACAO_COMPRA, S.DE_SITUACAO_COMPRA)@

MERGE INTO LCE.LCETB052_TIPO_COMBO AS T
USING (
  VALUES
    (1, 'ESPECIAL', 'ESPECIAL', 1, CURRENT DATE, 'S'),
    (2, 'SUPER_MILIONARIO', 'SUPER_MILIONARIO', 2, CURRENT DATE, 'S'),
    (3, 'MILIONARIO', 'MILIONARIO', 3, CURRENT DATE, 'S'),
    (4, 'MUITO_DINHEIRO', 'MUITO_DINHEIRO', 4, CURRENT DATE, 'S'),
    (5, 'SORTE_FACIL', 'SORTE_FACIL', 5, CURRENT DATE, 'S'),
    (6, 'CHANCE_TODO_DIA', 'CHANCE_TODO_DIA', 6, CURRENT DATE, 'S'),
    (7, 'SORTE_ACUMULADA', 'SORTE_ACUMULADA', 7, CURRENT DATE, 'S'),
    (8, 'SORTE_HOJE', 'SORTE_HOJE', 8, CURRENT DATE, 'S'),
    (9, 'FEZINHA_DO_MES', 'FEZINHA_DO_MES', 9, CURRENT DATE, 'S'),
    (10, 'VIP', 'VIP', 10, CURRENT DATE, 'S'),
    (11, 'CAIXA_PRA_ELAS', 'CAIXA_PRA_ELAS', 11, CURRENT DATE, 'S')
) AS S(NU_TIPO_COMBO, NO_TIPO_COMBO, DE_TIPO_COMBO, NU_ORDEM_TIPO_COMBO, DT_CRIACAO_TIPO_COMBO, IC_TIPO_COMBO_DISPONIVEL)
ON T.NU_TIPO_COMBO = S.NU_TIPO_COMBO
WHEN MATCHED THEN
  UPDATE SET
    NO_TIPO_COMBO = S.NO_TIPO_COMBO,
    DE_TIPO_COMBO = S.DE_TIPO_COMBO,
    NU_ORDEM_TIPO_COMBO = S.NU_ORDEM_TIPO_COMBO,
    DT_CRIACAO_TIPO_COMBO = S.DT_CRIACAO_TIPO_COMBO,
    IC_TIPO_COMBO_DISPONIVEL = S.IC_TIPO_COMBO_DISPONIVEL
WHEN NOT MATCHED THEN
  INSERT (NU_TIPO_COMBO, NO_TIPO_COMBO, DE_TIPO_COMBO, NU_ORDEM_TIPO_COMBO, DT_CRIACAO_TIPO_COMBO, IC_TIPO_COMBO_DISPONIVEL)
  VALUES (S.NU_TIPO_COMBO, S.NO_TIPO_COMBO, S.DE_TIPO_COMBO, S.NU_ORDEM_TIPO_COMBO, S.DT_CRIACAO_TIPO_COMBO, S.IC_TIPO_COMBO_DISPONIVEL)@

MERGE INTO LCE.LCETB008_SITUACAO_APOSTA AS T
USING (VALUES (1, 'NAO_REGISTRADA')) AS S(NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
ON T.NU_SITUACAO_APOSTA = S.NU_SITUACAO_APOSTA
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
  VALUES (S.NU_SITUACAO_APOSTA, S.DE_SITUACAO_APOSTA)@

MERGE INTO LCE.LCETB008_SITUACAO_APOSTA AS T
USING (VALUES (8, 'REGISTRADA')) AS S(NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
ON T.NU_SITUACAO_APOSTA = S.NU_SITUACAO_APOSTA
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_APOSTA, DE_SITUACAO_APOSTA)
  VALUES (S.NU_SITUACAO_APOSTA, S.DE_SITUACAO_APOSTA)@

MERGE INTO LCE.LCETB060_STCO_RVRSA_COTA_BOLAO AS T
USING (
  VALUES
    (1, 'INICIADA', 'INICIADA'),
    (2, 'RESERVADA', 'RESERVADA'),
    (3, 'CANCELADA', 'CANCELADA'),
    (4, 'EM_PAGAMENTO', 'EM_PAGAMENTO'),
    (5, 'CONFIRMADA', 'CONFIRMADA'),
    (6, 'EM_CANCELAMENTO', 'EM_CANCELAMENTO'),
    (7, 'CONTABILIZADA', 'CONTABILIZADA')
) AS S(NU_SITUACAO_RESERVA_COTA_BOLAO, NO_RESERVA_SITUACAO_COTA_BOLAO, DE_SITUACAO_RESERVA_COTA_BOLAO)
ON T.NU_SITUACAO_RESERVA_COTA_BOLAO = S.NU_SITUACAO_RESERVA_COTA_BOLAO
WHEN MATCHED THEN
  UPDATE SET
    NO_RESERVA_SITUACAO_COTA_BOLAO = S.NO_RESERVA_SITUACAO_COTA_BOLAO,
    DE_SITUACAO_RESERVA_COTA_BOLAO = S.DE_SITUACAO_RESERVA_COTA_BOLAO
WHEN NOT MATCHED THEN
  INSERT (NU_SITUACAO_RESERVA_COTA_BOLAO, NO_RESERVA_SITUACAO_COTA_BOLAO, DE_SITUACAO_RESERVA_COTA_BOLAO)
  VALUES (S.NU_SITUACAO_RESERVA_COTA_BOLAO, S.NO_RESERVA_SITUACAO_COTA_BOLAO, S.DE_SITUACAO_RESERVA_COTA_BOLAO)@
